# We need sudo rights to setup testing environment correctly
sudo: required

# And the language is node.js :D
language: node_js

# Node.js versions that we're testing
node_js:
  - "stable"
  - "6"

# OS that we're testing
os:
  - linux
  - osx

# Before install we need to do some OS specified stuff
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - cp src/app/config/config.ts_example src/app/config/config.ts

# Before actual tests we need to install angular-cli and finally start window manager if tests are run on linux
before_script:
  - npm install -g @angular/cli
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

# Actual test script, note that we need to pass --watch=false option for this
script:
  - ng lint && ng test --watch=false --code-coverage

# And please send emails on errors
notifications:
  email: true

# whitelisted branches
branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
